Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 13, in main
    tracker.print_last_score()
  File "main.py", line 8, in print_last_score
    print("Last score:", self.scores[len(self.scores)])
                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
