Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 18, in main
    user.display_timeout()
  File "main.py", line 8, in display_timeout
    print("Timeout is set to:", self.profile['timeout'])
                                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'timeout'
